package waflib

import (
	"net/http"
	"testing"
)

func TestMatchSignaturesHeaders(t *testing.T) {
	sigs := []Signature{
		{Name: "Cloudflare", Headers: []string{"cf-ray", "cf-cache-status"}},
		{Name: "Akamai", Headers: []string{"x-akamai-transformed"}},
	}

	headers := http.Header{}
	headers.Set("CF-RAY", "abc123")
	headers.Set("Server", "cloudflare")

	detections := MatchSignatures(sigs, headers, nil)
	if len(detections) != 1 {
		t.Fatalf("expected 1 detection, got %d", len(detections))
	}
	if detections[0].Name != "Cloudflare" {
		t.Fatalf("expected Cloudflare, got %s", detections[0].Name)
	}
}

func TestMatchSignaturesBody(t *testing.T) {
	sigs := []Signature{
		{Name: "ModSecurity", BodyWords: []string{"Mod_Security"}},
	}

	detections := MatchSignatures(sigs, http.Header{}, []byte("This error was generated by Mod_Security"))
	if len(detections) != 1 {
		t.Fatalf("expected 1 detection, got %d", len(detections))
	}
}

func TestMatchSignaturesNoMatch(t *testing.T) {
	sigs := []Signature{
		{Name: "Cloudflare", Headers: []string{"cf-ray"}},
	}

	headers := http.Header{}
	headers.Set("Server", "nginx")

	detections := MatchSignatures(sigs, headers, []byte("hello"))
	if len(detections) != 0 {
		t.Fatalf("expected 0 detections, got %d", len(detections))
	}
}

func TestLoadSignatures(t *testing.T) {
	sigs, err := LoadSignatures("../../../waf_signatures.yaml")
	if err != nil {
		t.Fatalf("load signatures: %v", err)
	}
	if len(sigs) == 0 {
		t.Fatal("expected non-empty signatures list")
	}
}
